Panic Soft
define ROOT     C:\Program Files\nxlog
define LOGFILE  %ROOT%\data\nxlog.log

Moduledir %ROOT%\modules
CacheDir  %ROOT%\data
Pidfile   %ROOT%\data\nxlog.pid
SpoolDir  %ROOT%\data
LogFile   %LOGFILE%

<Extension syslog>
    Module      xm_syslog
</Extension>

<Input in>
    Module      im_msvistalog
</Input>

<Output out>
    Module      om_udp
    Host        192.168.227.137    
    Port        514                 
    Exec        to_syslog_bsd();
</Output>

<Route 1>
    Path        in => out
</Route>
